#include "pin.H"
extern "C" {
#include <lua.h>
}
#include <map>
using namespace std;
static void error(lua_State* L, string val){
lua_pushstring(L,("unable to find define "+val+" in enum REG").c_str());
lua_error(L);
}
static map<string,REG> init_map(){
	map<string,REG> smap;
	#ifdef TARGET_IA32E 
	smap["BPL"]=REG_BPL;
	smap["DIL"]=REG_DIL;
	smap["INST_G0D"]=REG_INST_G0D;
	smap["INST_G10D"]=REG_INST_G10D;
	smap["INST_G11D"]=REG_INST_G11D;
	smap["INST_G12D"]=REG_INST_G12D;
	smap["INST_G13D"]=REG_INST_G13D;
	smap["INST_G14D"]=REG_INST_G14D;
	smap["INST_G15D"]=REG_INST_G15D;
	smap["INST_G16D"]=REG_INST_G16D;
	smap["INST_G17D"]=REG_INST_G17D;
	smap["INST_G18D"]=REG_INST_G18D;
	smap["INST_G19D"]=REG_INST_G19D;
	smap["INST_G1D"]=REG_INST_G1D;
	smap["INST_G2D"]=REG_INST_G2D;
	smap["INST_G3D"]=REG_INST_G3D;
	smap["INST_G4D"]=REG_INST_G4D;
	smap["INST_G5D"]=REG_INST_G5D;
	smap["INST_G6D"]=REG_INST_G6D;
	smap["INST_G7D"]=REG_INST_G7D;
	smap["INST_G8D"]=REG_INST_G8D;
	smap["INST_G9D"]=REG_INST_G9D;
	smap["ORIG_RAX"]=REG_ORIG_RAX;
	smap["PIN_BPL"]=REG_PIN_BPL;
	smap["PIN_DIL"]=REG_PIN_DIL;
	smap["PIN_R10"]=REG_PIN_R10;
	smap["PIN_R10B"]=REG_PIN_R10B;
	smap["PIN_R10D"]=REG_PIN_R10D;
	smap["PIN_R10W"]=REG_PIN_R10W;
	smap["PIN_R11"]=REG_PIN_R11;
	smap["PIN_R11B"]=REG_PIN_R11B;
	smap["PIN_R11D"]=REG_PIN_R11D;
	smap["PIN_R11W"]=REG_PIN_R11W;
	smap["PIN_R12"]=REG_PIN_R12;
	smap["PIN_R12B"]=REG_PIN_R12B;
	smap["PIN_R12D"]=REG_PIN_R12D;
	smap["PIN_R12W"]=REG_PIN_R12W;
	smap["PIN_R13"]=REG_PIN_R13;
	smap["PIN_R13B"]=REG_PIN_R13B;
	smap["PIN_R13D"]=REG_PIN_R13D;
	smap["PIN_R13W"]=REG_PIN_R13W;
	smap["PIN_R14"]=REG_PIN_R14;
	smap["PIN_R14B"]=REG_PIN_R14B;
	smap["PIN_R14D"]=REG_PIN_R14D;
	smap["PIN_R14W"]=REG_PIN_R14W;
	smap["PIN_R15"]=REG_PIN_R15;
	smap["PIN_R15B"]=REG_PIN_R15B;
	smap["PIN_R15D"]=REG_PIN_R15D;
	smap["PIN_R15W"]=REG_PIN_R15W;
	smap["PIN_R8"]=REG_PIN_R8;
	smap["PIN_R8B"]=REG_PIN_R8B;
	smap["PIN_R8D"]=REG_PIN_R8D;
	smap["PIN_R8W"]=REG_PIN_R8W;
	smap["PIN_R9"]=REG_PIN_R9;
	smap["PIN_R9B"]=REG_PIN_R9B;
	smap["PIN_R9D"]=REG_PIN_R9D;
	smap["PIN_R9W"]=REG_PIN_R9W;
	smap["PIN_RBP"]=REG_PIN_RBP;
	smap["PIN_RBX"]=REG_PIN_RBX;
	smap["PIN_RSI"]=REG_PIN_RSI;
	smap["PIN_RSP"]=REG_PIN_RSP;
	smap["PIN_SIL"]=REG_PIN_SIL;
	smap["PIN_SPL"]=REG_PIN_SPL;
	smap["PIN_XMM10"]=REG_PIN_XMM10;
	smap["PIN_XMM11"]=REG_PIN_XMM11;
	smap["PIN_XMM12"]=REG_PIN_XMM12;
	smap["PIN_XMM13"]=REG_PIN_XMM13;
	smap["PIN_XMM14"]=REG_PIN_XMM14;
	smap["PIN_XMM15"]=REG_PIN_XMM15;
	smap["PIN_XMM8"]=REG_PIN_XMM8;
	smap["PIN_XMM9"]=REG_PIN_XMM9;
	smap["PIN_YMM10"]=REG_PIN_YMM10;
	smap["PIN_YMM11"]=REG_PIN_YMM11;
	smap["PIN_YMM12"]=REG_PIN_YMM12;
	smap["PIN_YMM13"]=REG_PIN_YMM13;
	smap["PIN_YMM14"]=REG_PIN_YMM14;
	smap["PIN_YMM15"]=REG_PIN_YMM15;
	smap["PIN_YMM8"]=REG_PIN_YMM8;
	smap["PIN_YMM9"]=REG_PIN_YMM9;
	smap["R10"]=REG_R10;
	smap["R10B"]=REG_R10B;
	smap["R10D"]=REG_R10D;
	smap["R10W"]=REG_R10W;
	smap["R11"]=REG_R11;
	smap["R11B"]=REG_R11B;
	smap["R11D"]=REG_R11D;
	smap["R11W"]=REG_R11W;
	smap["R12"]=REG_R12;
	smap["R12B"]=REG_R12B;
	smap["R12D"]=REG_R12D;
	smap["R12W"]=REG_R12W;
	smap["R13"]=REG_R13;
	smap["R13B"]=REG_R13B;
	smap["R13D"]=REG_R13D;
	smap["R13W"]=REG_R13W;
	smap["R14"]=REG_R14;
	smap["R14B"]=REG_R14B;
	smap["R14D"]=REG_R14D;
	smap["R14W"]=REG_R14W;
	smap["R15"]=REG_R15;
	smap["R15B"]=REG_R15B;
	smap["R15D"]=REG_R15D;
	smap["R15W"]=REG_R15W;
	smap["R8"]=REG_R8;
	smap["R8B"]=REG_R8B;
	smap["R8D"]=REG_R8D;
	smap["R8W"]=REG_R8W;
	smap["R9"]=REG_R9;
	smap["R9B"]=REG_R9B;
	smap["R9D"]=REG_R9D;
	smap["R9W"]=REG_R9W;
	smap["SIL"]=REG_SIL;
	smap["SPL"]=REG_SPL;
	smap["XMM10"]=REG_XMM10;
	smap["XMM11"]=REG_XMM11;
	smap["XMM12"]=REG_XMM12;
	smap["XMM13"]=REG_XMM13;
	smap["XMM14"]=REG_XMM14;
	smap["XMM15"]=REG_XMM15;
	smap["XMM8"]=REG_XMM8;
	smap["XMM9"]=REG_XMM9;
	smap["YMM10"]=REG_YMM10;
	smap["YMM11"]=REG_YMM11;
	smap["YMM12"]=REG_YMM12;
	smap["YMM13"]=REG_YMM13;
	smap["YMM14"]=REG_YMM14;
	smap["YMM15"]=REG_YMM15;
	smap["YMM8"]=REG_YMM8;
	smap["YMM9"]=REG_YMM9;
	//endif TARGET_HOST with 64 bits
	#endif
	smap["AH"]=REG_AH;
	smap["AL"]=REG_AL;
	smap["AX"]=REG_AX;
	smap["BH"]=REG_BH;
	smap["BL"]=REG_BL;
	smap["BP"]=REG_BP;
	smap["BUF_BASE0"]=REG_BUF_BASE0;
	smap["BUF_BASE1"]=REG_BUF_BASE1;
	smap["BUF_BASE2"]=REG_BUF_BASE2;
	smap["BUF_BASE3"]=REG_BUF_BASE3;
	smap["BUF_BASE4"]=REG_BUF_BASE4;
	smap["BUF_BASE5"]=REG_BUF_BASE5;
	smap["BUF_BASE6"]=REG_BUF_BASE6;
	smap["BUF_BASE7"]=REG_BUF_BASE7;
	smap["BUF_BASE8"]=REG_BUF_BASE8;
	smap["BUF_BASE9"]=REG_BUF_BASE9;
	smap["BUF_END0"]=REG_BUF_END0;
	smap["BUF_END1"]=REG_BUF_END1;
	smap["BUF_END2"]=REG_BUF_END2;
	smap["BUF_END3"]=REG_BUF_END3;
	smap["BUF_END4"]=REG_BUF_END4;
	smap["BUF_END5"]=REG_BUF_END5;
	smap["BUF_END6"]=REG_BUF_END6;
	smap["BUF_END7"]=REG_BUF_END7;
	smap["BUF_END8"]=REG_BUF_END8;
	smap["BUF_END9"]=REG_BUF_END9;
	smap["BX"]=REG_BX;
	smap["CH"]=REG_CH;
	smap["CL"]=REG_CL;
	smap["CR0"]=REG_CR0;
	smap["CR1"]=REG_CR1;
	smap["CR2"]=REG_CR2;
	smap["CR3"]=REG_CR3;
	smap["CR4"]=REG_CR4;
	smap["CX"]=REG_CX;
	smap["DF_FLAG"]=REG_DF_FLAG;
	smap["DH"]=REG_DH;
	smap["DI"]=REG_DI;
	smap["DL"]=REG_DL;
	smap["DR0"]=REG_DR0;
	smap["DR1"]=REG_DR1;
	smap["DR2"]=REG_DR2;
	smap["DR3"]=REG_DR3;
	smap["DR4"]=REG_DR4;
	smap["DR5"]=REG_DR5;
	smap["DR6"]=REG_DR6;
	smap["DR7"]=REG_DR7;
	smap["DX"]=REG_DX;
	smap["EAX"]=REG_EAX;
	smap["EBP"]=REG_EBP;
	smap["EBX"]=REG_EBX;
	smap["ECX"]=REG_ECX;
	smap["EDI"]=REG_EDI;
	smap["EDX"]=REG_EDX;
	smap["EFLAGS"]=REG_EFLAGS;
	smap["EIP"]=REG_EIP;
	smap["EMM0"]=REG_EMM0;
	smap["EMM1"]=REG_EMM1;
	smap["EMM2"]=REG_EMM2;
	smap["EMM3"]=REG_EMM3;
	smap["EMM4"]=REG_EMM4;
	smap["EMM5"]=REG_EMM5;
	smap["EMM6"]=REG_EMM6;
	smap["EMM7"]=REG_EMM7;
	smap["ESI"]=REG_ESI;
	smap["ESP"]=REG_ESP;
	smap["FLAGS"]=REG_FLAGS;
	smap["FLAGS_BEFORE_AC_CLEARING"]=REG_FLAGS_BEFORE_AC_CLEARING;
	smap["FPCW"]=REG_FPCW;
	smap["FPDP_OFF"]=REG_FPDP_OFF;
	smap["FPDP_SEL"]=REG_FPDP_SEL;
	smap["FPIP_OFF"]=REG_FPIP_OFF;
	smap["FPIP_SEL"]=REG_FPIP_SEL;
	smap["FPOPCODE"]=REG_FPOPCODE;
	smap["FPSW"]=REG_FPSW;
	smap["FPTAG"]=REG_FPTAG;
	smap["FPTAG_FULL"]=REG_FPTAG_FULL;
	smap["GAX"]=REG_GAX;
	smap["GBP"]=REG_GBP;
	smap["GBX"]=REG_GBX;
	smap["GCX"]=REG_GCX;
	smap["GDI"]=REG_GDI;
	smap["GDX"]=REG_GDX;
	smap["GFLAGS"]=REG_GFLAGS;
	smap["GSI"]=REG_GSI;
	smap["IMM"]=REG_IMM;
	smap["IMM32"]=REG_IMM32;
	smap["IMM8"]=REG_IMM8;
	smap["INST_COND"]=REG_INST_COND;
	smap["INST_G1"]=REG_INST_G1;
	smap["INST_G10"]=REG_INST_G10;
	smap["INST_G11"]=REG_INST_G11;
	smap["INST_G12"]=REG_INST_G12;
	smap["INST_G13"]=REG_INST_G13;
	smap["INST_G14"]=REG_INST_G14;
	smap["INST_G15"]=REG_INST_G15;
	smap["INST_G16"]=REG_INST_G16;
	smap["INST_G17"]=REG_INST_G17;
	smap["INST_G18"]=REG_INST_G18;
	smap["INST_G19"]=REG_INST_G19;
	smap["INST_G2"]=REG_INST_G2;
	smap["INST_G3"]=REG_INST_G3;
	smap["INST_G4"]=REG_INST_G4;
	smap["INST_G5"]=REG_INST_G5;
	smap["INST_G6"]=REG_INST_G6;
	smap["INST_G7"]=REG_INST_G7;
	smap["INST_G8"]=REG_INST_G8;
	smap["INST_G9"]=REG_INST_G9;
	smap["INST_PRESERVED_PREDICATE"]=REG_INST_PRESERVED_PREDICATE;
	smap["INST_PTR"]=REG_INST_PTR;
	smap["INST_T0"]=REG_INST_T0;
	smap["INST_T0D"]=REG_INST_T0D;
	smap["INST_T0L"]=REG_INST_T0L;
	smap["INST_T0W"]=REG_INST_T0W;
	smap["INST_T1"]=REG_INST_T1;
	smap["INST_T1D"]=REG_INST_T1D;
	smap["INST_T1L"]=REG_INST_T1L;
	smap["INST_T1W"]=REG_INST_T1W;
	smap["INST_T2"]=REG_INST_T2;
	smap["INST_T2D"]=REG_INST_T2D;
	smap["INST_T2L"]=REG_INST_T2L;
	smap["INST_T2W"]=REG_INST_T2W;
	smap["INST_T3"]=REG_INST_T3;
	smap["INST_T3D"]=REG_INST_T3D;
	smap["INST_T3L"]=REG_INST_T3L;
	smap["INST_T3W"]=REG_INST_T3W;
	smap["INST_TOOL_FIRST"]=REG_INST_TOOL_FIRST;
	smap["INVALID_"]=REG_INVALID_;
	smap["IP"]=REG_IP;
	smap["LAST"]=REG_LAST;
	smap["LDTR"]=REG_LDTR;
	smap["MEM"]=REG_MEM;
	smap["MEM_OFF32"]=REG_MEM_OFF32;
	smap["MEM_OFF8"]=REG_MEM_OFF8;
	smap["MM0"]=REG_MM0;
	smap["MM1"]=REG_MM1;
	smap["MM2"]=REG_MM2;
	smap["MM3"]=REG_MM3;
	smap["MM4"]=REG_MM4;
	smap["MM5"]=REG_MM5;
	smap["MM6"]=REG_MM6;
	smap["MM7"]=REG_MM7;
	smap["MODX"]=REG_MODX;
	smap["MXCSR"]=REG_MXCSR;
	smap["MXCSRMASK"]=REG_MXCSRMASK;
	smap["MXT"]=REG_MXT;
	smap["NONE"]=REG_NONE;
	smap["OFF"]=REG_OFF;
	smap["OFF32"]=REG_OFF32;
	smap["OFF8"]=REG_OFF8;
	smap["PIN_AH"]=REG_PIN_AH;
	smap["PIN_AL"]=REG_PIN_AL;
	smap["PIN_AX"]=REG_PIN_AX;
	smap["PIN_BH"]=REG_PIN_BH;
	smap["PIN_BL"]=REG_PIN_BL;
	smap["PIN_BP"]=REG_PIN_BP;
	smap["PIN_BRIDGE_APP_IP"]=REG_PIN_BRIDGE_APP_IP;
	smap["PIN_BRIDGE_MARSHALLING_FRAME"]=REG_PIN_BRIDGE_MARSHALLING_FRAME;
	smap["PIN_BRIDGE_MULTI_MEMORYACCESS_FRAME"]=REG_PIN_BRIDGE_MULTI_MEMORYACCESS_FRAME;
	smap["PIN_BRIDGE_MULTI_MEMORYACCESS_SP"]=REG_PIN_BRIDGE_MULTI_MEMORYACCESS_SP;
	smap["PIN_BRIDGE_ON_STACK_CONTEXT_FRAME"]=REG_PIN_BRIDGE_ON_STACK_CONTEXT_FRAME;
	smap["PIN_BRIDGE_ON_STACK_CONTEXT_SP"]=REG_PIN_BRIDGE_ON_STACK_CONTEXT_SP;
	smap["PIN_BRIDGE_ORIG_SP"]=REG_PIN_BRIDGE_ORIG_SP;
	smap["PIN_BRIDGE_SP_BEFORE_ALIGN"]=REG_PIN_BRIDGE_SP_BEFORE_ALIGN;
	smap["PIN_BRIDGE_SP_BEFORE_CALL"]=REG_PIN_BRIDGE_SP_BEFORE_CALL;
	smap["PIN_BRIDGE_SPILL_AREA_CONTEXT_FRAME"]=REG_PIN_BRIDGE_SPILL_AREA_CONTEXT_FRAME;
	smap["PIN_BRIDGE_SPILL_AREA_CONTEXT_SP"]=REG_PIN_BRIDGE_SPILL_AREA_CONTEXT_SP;
	smap["PIN_BRIDGE_TRANS_MEMORY_CALLBACK_FRAME"]=REG_PIN_BRIDGE_TRANS_MEMORY_CALLBACK_FRAME;
	smap["PIN_BRIDGE_TRANS_MEMORY_CALLBACK_SP"]=REG_PIN_BRIDGE_TRANS_MEMORY_CALLBACK_SP;
	smap["PIN_BX"]=REG_PIN_BX;
	smap["PIN_CH"]=REG_PIN_CH;
	smap["PIN_CL"]=REG_PIN_CL;
	smap["PIN_CX"]=REG_PIN_CX;
	smap["PIN_DF_FLAG"]=REG_PIN_DF_FLAG;
	smap["PIN_DH"]=REG_PIN_DH;
	smap["PIN_DI"]=REG_PIN_DI;
	smap["PIN_DL"]=REG_PIN_DL;
	smap["PIN_DX"]=REG_PIN_DX;
	smap["PIN_EAX"]=REG_PIN_EAX;
	smap["PIN_EBP"]=REG_PIN_EBP;
	smap["PIN_EBX"]=REG_PIN_EBX;
	smap["PIN_ECX"]=REG_PIN_ECX;
	smap["PIN_EDI"]=REG_PIN_EDI;
	smap["PIN_EDX"]=REG_PIN_EDX;
	smap["PIN_ESI"]=REG_PIN_ESI;
	smap["PIN_ESP"]=REG_PIN_ESP;
	smap["PIN_FLAGS"]=REG_PIN_FLAGS;
	smap["PIN_GAX"]=REG_PIN_GAX;
	smap["PIN_GCX"]=REG_PIN_GCX;
	smap["PIN_GDI"]=REG_PIN_GDI;
	smap["PIN_GDX"]=REG_PIN_GDX;
	smap["PIN_INDIRREG"]=REG_PIN_INDIRREG;
	smap["PIN_IPRELADDR"]=REG_PIN_IPRELADDR;
	smap["PIN_MULTI_MEM_ACCESS_AND_REWRITE_EMULATION_INFO_FRAME"]=REG_PIN_MULTI_MEM_ACCESS_AND_REWRITE_EMULATION_INFO_FRAME;
	smap["PIN_MXCSR"]=REG_PIN_MXCSR;
	smap["PIN_SI"]=REG_PIN_SI;
	smap["PIN_SP"]=REG_PIN_SP;
	smap["PIN_SPILLPTR"]=REG_PIN_SPILLPTR;
	smap["PIN_STATUS_FLAGS"]=REG_PIN_STATUS_FLAGS;
	smap["PIN_SYSENTER_RESUMEADDR"]=REG_PIN_SYSENTER_RESUMEADDR;
	smap["PIN_T0"]=REG_PIN_T0;
	smap["PIN_T0D"]=REG_PIN_T0D;
	smap["PIN_T0L"]=REG_PIN_T0L;
	smap["PIN_T0W"]=REG_PIN_T0W;
	smap["PIN_T1"]=REG_PIN_T1;
	smap["PIN_T1D"]=REG_PIN_T1D;
	smap["PIN_T1L"]=REG_PIN_T1L;
	smap["PIN_T1W"]=REG_PIN_T1W;
	smap["PIN_T2"]=REG_PIN_T2;
	smap["PIN_T2D"]=REG_PIN_T2D;
	smap["PIN_T2L"]=REG_PIN_T2L;
	smap["PIN_T2W"]=REG_PIN_T2W;
	smap["PIN_T3"]=REG_PIN_T3;
	smap["PIN_T3D"]=REG_PIN_T3D;
	smap["PIN_T3L"]=REG_PIN_T3L;
	smap["PIN_T3W"]=REG_PIN_T3W;
	smap["PIN_TRANS_MEMORY_CALLBACK_READ2_ADDR"]=REG_PIN_TRANS_MEMORY_CALLBACK_READ2_ADDR;
	smap["PIN_TRANS_MEMORY_CALLBACK_READ_ADDR"]=REG_PIN_TRANS_MEMORY_CALLBACK_READ_ADDR;
	smap["PIN_TRANS_MEMORY_CALLBACK_WRITE_ADDR"]=REG_PIN_TRANS_MEMORY_CALLBACK_WRITE_ADDR;
	smap["PIN_VMENTER"]=REG_PIN_VMENTER;
	smap["PIN_X87"]=REG_PIN_X87;
	smap["PIN_XMM0"]=REG_PIN_XMM0;
	smap["PIN_XMM1"]=REG_PIN_XMM1;
	smap["PIN_XMM2"]=REG_PIN_XMM2;
	smap["PIN_XMM3"]=REG_PIN_XMM3;
	smap["PIN_XMM4"]=REG_PIN_XMM4;
	smap["PIN_XMM5"]=REG_PIN_XMM5;
	smap["PIN_XMM6"]=REG_PIN_XMM6;
	smap["PIN_XMM7"]=REG_PIN_XMM7;
	smap["PIN_YMM0"]=REG_PIN_YMM0;
	smap["PIN_YMM1"]=REG_PIN_YMM1;
	smap["PIN_YMM2"]=REG_PIN_YMM2;
	smap["PIN_YMM3"]=REG_PIN_YMM3;
	smap["PIN_YMM4"]=REG_PIN_YMM4;
	smap["PIN_YMM5"]=REG_PIN_YMM5;
	smap["PIN_YMM6"]=REG_PIN_YMM6;
	smap["PIN_YMM7"]=REG_PIN_YMM7;
	smap["SEG_CS"]=REG_SEG_CS;
	smap["SEG_DS"]=REG_SEG_DS;
	smap["SEG_ES"]=REG_SEG_ES;
	smap["SEG_FS"]=REG_SEG_FS;
	smap["SEG_FS_BASE"]=REG_SEG_FS_BASE;
	smap["SEG_FS_VAL"]=REG_SEG_FS_VAL;
	smap["SEG_GS"]=REG_SEG_GS;
	smap["SEG_GS_BASE"]=REG_SEG_GS_BASE;
	smap["SEG_GS_VAL"]=REG_SEG_GS_VAL;
	smap["SEG_SS"]=REG_SEG_SS;
	smap["SI"]=REG_SI;
	smap["SP"]=REG_SP;
	smap["ST0"]=REG_ST0;
	smap["ST1"]=REG_ST1;
	smap["ST2"]=REG_ST2;
	smap["ST3"]=REG_ST3;
	smap["ST4"]=REG_ST4;
	smap["ST5"]=REG_ST5;
	smap["ST6"]=REG_ST6;
	smap["ST7"]=REG_ST7;
	smap["STACK_PTR"]=REG_STACK_PTR;
	smap["STATUS_FLAGS"]=REG_STATUS_FLAGS;
	smap["THREAD_ID"]=REG_THREAD_ID;
	smap["TR"]=REG_TR;
	smap["TR3"]=REG_TR3;
	smap["TR4"]=REG_TR4;
	smap["TR5"]=REG_TR5;
	smap["TR6"]=REG_TR6;
	smap["TR7"]=REG_TR7;
	smap["TSSR"]=REG_TSSR;
	smap["X87"]=REG_X87;
	smap["XMM0"]=REG_XMM0;
	smap["XMM1"]=REG_XMM1;
	smap["XMM2"]=REG_XMM2;
	smap["XMM3"]=REG_XMM3;
	smap["XMM4"]=REG_XMM4;
	smap["XMM5"]=REG_XMM5;
	smap["XMM6"]=REG_XMM6;
	smap["XMM7"]=REG_XMM7;
	smap["YMM0"]=REG_YMM0;
	smap["YMM1"]=REG_YMM1;
	smap["YMM2"]=REG_YMM2;
	smap["YMM3"]=REG_YMM3;
	smap["YMM4"]=REG_YMM4;
	smap["YMM5"]=REG_YMM5;
	smap["YMM6"]=REG_YMM6;
	smap["YMM7"]=REG_YMM7;
	return smap;
}
REG lookup_string_to_reg(lua_State *L, string str){
  static const map<string,REG> sym_map = init_map();
  if(sym_map.find(str)!=sym_map.end()){
    return sym_map.find(str)->second;
  }
 error(L,str);
 return sym_map.begin()->second; //this will never be reached just to prevent compiler warning
}
string lookup_reg_to_string(lua_State* L,REG sym) {
 switch (sym) {
 	#ifdef TARGET_IA32E
    case(REG_BPL): return "BPL";
    case(REG_DIL): return "DIL";
    case(REG_GAX): return "GAX";
    case(REG_GBP): return "GBP";
    case(REG_GBX): return "GBX";
    case(REG_GCX): return "GCX";
    case(REG_GDI): return "GDI";
    case(REG_GDX): return "GDX";
    case(REG_GFLAGS): return "GFLAGS";
    case(REG_GSI): return "GSI";
    case(REG_INST_G0D): return "INST_G0D";
    case(REG_INST_G10D): return "INST_G10D";
    case(REG_INST_G11D): return "INST_G11D";
    case(REG_INST_G12D): return "INST_G12D";
    case(REG_INST_G13D): return "INST_G13D";
    case(REG_INST_G14D): return "INST_G14D";
    case(REG_INST_G15D): return "INST_G15D";
    case(REG_INST_G16D): return "INST_G16D";
    case(REG_INST_G17D): return "INST_G17D";
    case(REG_INST_G18D): return "INST_G18D";
    case(REG_INST_G19D): return "INST_G19D";
    case(REG_INST_G1D): return "INST_G1D";
    case(REG_INST_G2D): return "INST_G2D";
    case(REG_INST_G3D): return "INST_G3D";
    case(REG_INST_G4D): return "INST_G4D";
    case(REG_INST_G5D): return "INST_G5D";
    case(REG_INST_G6D): return "INST_G6D";
    case(REG_INST_G7D): return "INST_G7D";
    case(REG_INST_G8D): return "INST_G8D";
    case(REG_INST_G9D): return "INST_G9D";
    case(REG_INST_PTR): return "INST_PTR";
    case(REG_ORIG_RAX): return "ORIG_RAX";
    case(REG_PIN_BPL): return "PIN_BPL";
    case(REG_PIN_DIL): return "PIN_DIL";
    case(REG_PIN_GAX): return "PIN_GAX";
    case(REG_PIN_GCX): return "PIN_GCX";
    case(REG_PIN_GDI): return "PIN_GDI";
    case(REG_PIN_GDX): return "PIN_GDX";
    case(REG_PIN_R10): return "PIN_R10";
    case(REG_PIN_R10B): return "PIN_R10B";
    case(REG_PIN_R10D): return "PIN_R10D";
    case(REG_PIN_R10W): return "PIN_R10W";
    case(REG_PIN_R11): return "PIN_R11";
    case(REG_PIN_R11B): return "PIN_R11B";
    case(REG_PIN_R11D): return "PIN_R11D";
    case(REG_PIN_R11W): return "PIN_R11W";
    case(REG_PIN_R12): return "PIN_R12";
    case(REG_PIN_R12B): return "PIN_R12B";
    case(REG_PIN_R12D): return "PIN_R12D";
    case(REG_PIN_R12W): return "PIN_R12W";
    case(REG_PIN_R13): return "PIN_R13";
    case(REG_PIN_R13B): return "PIN_R13B";
    case(REG_PIN_R13D): return "PIN_R13D";
    case(REG_PIN_R13W): return "PIN_R13W";
    case(REG_PIN_R14): return "PIN_R14";
    case(REG_PIN_R14B): return "PIN_R14B";
    case(REG_PIN_R14D): return "PIN_R14D";
    case(REG_PIN_R14W): return "PIN_R14W";
    case(REG_PIN_R15): return "PIN_R15";
    case(REG_PIN_R15B): return "PIN_R15B";
    case(REG_PIN_R15D): return "PIN_R15D";
    case(REG_PIN_R15W): return "PIN_R15W";
    case(REG_PIN_R8): return "PIN_R8";
    case(REG_PIN_R8B): return "PIN_R8B";
    case(REG_PIN_R8D): return "PIN_R8D";
    case(REG_PIN_R8W): return "PIN_R8W";
    case(REG_PIN_R9): return "PIN_R9";
    case(REG_PIN_R9B): return "PIN_R9B";
    case(REG_PIN_R9D): return "PIN_R9D";
    case(REG_PIN_R9W): return "PIN_R9W";
    case(REG_PIN_RBP): return "PIN_RBP";
    case(REG_PIN_RBX): return "PIN_RBX";
    case(REG_PIN_RSI): return "PIN_RSI";
    case(REG_PIN_RSP): return "PIN_RSP";
    case(REG_PIN_SIL): return "PIN_SIL";
    case(REG_PIN_SPL): return "PIN_SPL";
    case(REG_PIN_XMM10): return "PIN_XMM10";
    case(REG_PIN_XMM11): return "PIN_XMM11";
    case(REG_PIN_XMM12): return "PIN_XMM12";
    case(REG_PIN_XMM13): return "PIN_XMM13";
    case(REG_PIN_XMM14): return "PIN_XMM14";
    case(REG_PIN_XMM15): return "PIN_XMM15";
    case(REG_PIN_XMM8): return "PIN_XMM8";
    case(REG_PIN_XMM9): return "PIN_XMM9";
    case(REG_PIN_YMM10): return "PIN_YMM10";
    case(REG_PIN_YMM11): return "PIN_YMM11";
    case(REG_PIN_YMM12): return "PIN_YMM12";
    case(REG_PIN_YMM13): return "PIN_YMM13";
    case(REG_PIN_YMM14): return "PIN_YMM14";
    case(REG_PIN_YMM15): return "PIN_YMM15";
    case(REG_PIN_YMM8): return "PIN_YMM8";
    case(REG_PIN_YMM9): return "PIN_YMM9";
    case(REG_R10): return "R10";
    case(REG_R10B): return "R10B";
    case(REG_R10D): return "R10D";
    case(REG_R10W): return "R10W";
    case(REG_R11): return "R11";
    case(REG_R11B): return "R11B";
    case(REG_R11D): return "R11D";
    case(REG_R11W): return "R11W";
    case(REG_R12): return "R12";
    case(REG_R12B): return "R12B";
    case(REG_R12D): return "R12D";
    case(REG_R12W): return "R12W";
    case(REG_R13): return "R13";
    case(REG_R13B): return "R13B";
    case(REG_R13D): return "R13D";
    case(REG_R13W): return "R13W";
    case(REG_R14): return "R14";
    case(REG_R14B): return "R14B";
    case(REG_R14D): return "R14D";
    case(REG_R14W): return "R14W";
    case(REG_R15): return "R15";
    case(REG_R15B): return "R15B";
    case(REG_R15D): return "R15D";
    case(REG_R15W): return "R15W";
    case(REG_R8): return "R8";
    case(REG_R8B): return "R8B";
    case(REG_R8D): return "R8D";
    case(REG_R8W): return "R8W";
    case(REG_R9): return "R9";
    case(REG_R9B): return "R9B";
    case(REG_R9D): return "R9D";
    case(REG_R9W): return "R9W";
    case(REG_SIL): return "SIL";
    case(REG_SPL): return "SPL";
    case(REG_STACK_PTR): return "STACK_PTR";
    case(REG_XMM10): return "XMM10";
    case(REG_XMM11): return "XMM11";
    case(REG_XMM12): return "XMM12";
    case(REG_XMM13): return "XMM13";
    case(REG_XMM14): return "XMM14";
    case(REG_XMM15): return "XMM15";
    case(REG_XMM8): return "XMM8";
    case(REG_XMM9): return "XMM9";
    case(REG_YMM10): return "YMM10";
    case(REG_YMM11): return "YMM11";
    case(REG_YMM12): return "YMM12";
    case(REG_YMM13): return "YMM13";
    case(REG_YMM14): return "YMM14";
    case(REG_YMM15): return "YMM15";
    case(REG_YMM8): return "YMM8";
    case(REG_YMM9): return "YMM9";
    #endif
    case(REG_AH): return "AH";
    case(REG_AL): return "AL";
    case(REG_AX): return "AX";
    case(REG_BH): return "BH";
    case(REG_BL): return "BL";
    case(REG_BP): return "BP";
    case(REG_BUF_BASE0): return "BUF_BASE0";
    case(REG_BUF_BASE1): return "BUF_BASE1";
    case(REG_BUF_BASE2): return "BUF_BASE2";
    case(REG_BUF_BASE3): return "BUF_BASE3";
    case(REG_BUF_BASE4): return "BUF_BASE4";
    case(REG_BUF_BASE5): return "BUF_BASE5";
    case(REG_BUF_BASE6): return "BUF_BASE6";
    case(REG_BUF_BASE7): return "BUF_BASE7";
    case(REG_BUF_BASE8): return "BUF_BASE8";
    case(REG_BUF_BASE9): return "BUF_BASE9";
    case(REG_BUF_END0): return "BUF_END0";
    case(REG_BUF_END1): return "BUF_END1";
    case(REG_BUF_END2): return "BUF_END2";
    case(REG_BUF_END3): return "BUF_END3";
    case(REG_BUF_END4): return "BUF_END4";
    case(REG_BUF_END5): return "BUF_END5";
    case(REG_BUF_END6): return "BUF_END6";
    case(REG_BUF_END7): return "BUF_END7";
    case(REG_BUF_END8): return "BUF_END8";
    case(REG_BUF_END9): return "BUF_END9";
    case(REG_BX): return "BX";
    case(REG_CH): return "CH";
    case(REG_CL): return "CL";
    case(REG_CR0): return "CR0";
    case(REG_CR1): return "CR1";
    case(REG_CR2): return "CR2";
    case(REG_CR3): return "CR3";
    case(REG_CR4): return "CR4";
    case(REG_CX): return "CX";
    case(REG_DF_FLAG): return "DF_FLAG";
    case(REG_DH): return "DH";
    case(REG_DI): return "DI";
    case(REG_DL): return "DL";
    case(REG_DR0): return "DR0";
    case(REG_DR1): return "DR1";
    case(REG_DR2): return "DR2";
    case(REG_DR3): return "DR3";
    case(REG_DR4): return "DR4";
    case(REG_DR5): return "DR5";
    case(REG_DR6): return "DR6";
    case(REG_DR7): return "DR7";
    case(REG_DX): return "DX";
    case(REG_EAX): return "EAX";
    case(REG_EBP): return "EBP";
    case(REG_EBX): return "EBX";
    case(REG_ECX): return "ECX";
    case(REG_EDI): return "EDI";
    case(REG_EDX): return "EDX";
    case(REG_EFLAGS): return "EFLAGS";
    case(REG_EIP): return "EIP";
    case(REG_EMM0): return "EMM0";
    case(REG_EMM1): return "EMM1";
    case(REG_EMM2): return "EMM2";
    case(REG_EMM3): return "EMM3";
    case(REG_EMM4): return "EMM4";
    case(REG_EMM5): return "EMM5";
    case(REG_EMM6): return "EMM6";
    case(REG_EMM7): return "EMM7";
    case(REG_ESI): return "ESI";
    case(REG_ESP): return "ESP";
    case(REG_FLAGS): return "FLAGS";
    case(REG_FLAGS_BEFORE_AC_CLEARING): return "FLAGS_BEFORE_AC_CLEARING";
    case(REG_FPCW): return "FPCW";
    case(REG_FPDP_OFF): return "FPDP_OFF";
    case(REG_FPDP_SEL): return "FPDP_SEL";
    case(REG_FPIP_OFF): return "FPIP_OFF";
    case(REG_FPIP_SEL): return "FPIP_SEL";
    case(REG_FPOPCODE): return "FPOPCODE";
    case(REG_FPSW): return "FPSW";
    case(REG_FPTAG): return "FPTAG";
    case(REG_FPTAG_FULL): return "FPTAG_FULL";
    case(REG_IMM): return "IMM";
    case(REG_IMM32): return "IMM32";
    case(REG_IMM8): return "IMM8";
    case(REG_INST_COND): return "INST_COND";
    case(REG_INST_G1): return "INST_G1";
    case(REG_INST_G10): return "INST_G10";
    case(REG_INST_G11): return "INST_G11";
    case(REG_INST_G12): return "INST_G12";
    case(REG_INST_G13): return "INST_G13";
    case(REG_INST_G14): return "INST_G14";
    case(REG_INST_G15): return "INST_G15";
    case(REG_INST_G16): return "INST_G16";
    case(REG_INST_G17): return "INST_G17";
    case(REG_INST_G18): return "INST_G18";
    case(REG_INST_G19): return "INST_G19";
    case(REG_INST_G2): return "INST_G2";
    case(REG_INST_G3): return "INST_G3";
    case(REG_INST_G4): return "INST_G4";
    case(REG_INST_G5): return "INST_G5";
    case(REG_INST_G6): return "INST_G6";
    case(REG_INST_G7): return "INST_G7";
    case(REG_INST_G8): return "INST_G8";
    case(REG_INST_G9): return "INST_G9";
    case(REG_INST_PRESERVED_PREDICATE): return "INST_PRESERVED_PREDICATE";
    case(REG_INST_T0): return "INST_T0";
    case(REG_INST_T0D): return "INST_T0D";
    case(REG_INST_T0L): return "INST_T0L";
    case(REG_INST_T0W): return "INST_T0W";
    case(REG_INST_T1): return "INST_T1";
    case(REG_INST_T1D): return "INST_T1D";
    case(REG_INST_T1L): return "INST_T1L";
    case(REG_INST_T1W): return "INST_T1W";
    case(REG_INST_T2): return "INST_T2";
    case(REG_INST_T2D): return "INST_T2D";
    case(REG_INST_T2L): return "INST_T2L";
    case(REG_INST_T2W): return "INST_T2W";
    case(REG_INST_T3): return "INST_T3";
    case(REG_INST_T3D): return "INST_T3D";
    case(REG_INST_T3L): return "INST_T3L";
    case(REG_INST_T3W): return "INST_T3W";
    case(REG_INST_TOOL_FIRST): return "INST_TOOL_FIRST";
    case(REG_INVALID_): return "INVALID_";
    case(REG_IP): return "IP";
    case(REG_LAST): return "LAST";
    case(REG_LDTR): return "LDTR";
    case(REG_MEM): return "MEM";
    case(REG_MEM_OFF32): return "MEM_OFF32";
    case(REG_MEM_OFF8): return "MEM_OFF8";
    case(REG_MM0): return "MM0";
    case(REG_MM1): return "MM1";
    case(REG_MM2): return "MM2";
    case(REG_MM3): return "MM3";
    case(REG_MM4): return "MM4";
    case(REG_MM5): return "MM5";
    case(REG_MM6): return "MM6";
    case(REG_MM7): return "MM7";
    case(REG_MODX): return "MODX";
    case(REG_MXCSR): return "MXCSR";
    case(REG_MXCSRMASK): return "MXCSRMASK";
    case(REG_MXT): return "MXT";
    case(REG_NONE): return "NONE";
    case(REG_OFF): return "OFF";
    case(REG_OFF32): return "OFF32";
    case(REG_OFF8): return "OFF8";
    case(REG_PIN_AH): return "PIN_AH";
    case(REG_PIN_AL): return "PIN_AL";
    case(REG_PIN_AX): return "PIN_AX";
    case(REG_PIN_BH): return "PIN_BH";
    case(REG_PIN_BL): return "PIN_BL";
    case(REG_PIN_BP): return "PIN_BP";
    case(REG_PIN_BRIDGE_APP_IP): return "PIN_BRIDGE_APP_IP";
    case(REG_PIN_BRIDGE_MARSHALLING_FRAME): return "PIN_BRIDGE_MARSHALLING_FRAME";
    case(REG_PIN_BRIDGE_MULTI_MEMORYACCESS_FRAME): return "PIN_BRIDGE_MULTI_MEMORYACCESS_FRAME";
    case(REG_PIN_BRIDGE_MULTI_MEMORYACCESS_SP): return "PIN_BRIDGE_MULTI_MEMORYACCESS_SP";
    case(REG_PIN_BRIDGE_ON_STACK_CONTEXT_FRAME): return "PIN_BRIDGE_ON_STACK_CONTEXT_FRAME";
    case(REG_PIN_BRIDGE_ON_STACK_CONTEXT_SP): return "PIN_BRIDGE_ON_STACK_CONTEXT_SP";
    case(REG_PIN_BRIDGE_ORIG_SP): return "PIN_BRIDGE_ORIG_SP";
    case(REG_PIN_BRIDGE_SP_BEFORE_ALIGN): return "PIN_BRIDGE_SP_BEFORE_ALIGN";
    case(REG_PIN_BRIDGE_SP_BEFORE_CALL): return "PIN_BRIDGE_SP_BEFORE_CALL";
    case(REG_PIN_BRIDGE_SPILL_AREA_CONTEXT_FRAME): return "PIN_BRIDGE_SPILL_AREA_CONTEXT_FRAME";
    case(REG_PIN_BRIDGE_SPILL_AREA_CONTEXT_SP): return "PIN_BRIDGE_SPILL_AREA_CONTEXT_SP";
    case(REG_PIN_BRIDGE_TRANS_MEMORY_CALLBACK_FRAME): return "PIN_BRIDGE_TRANS_MEMORY_CALLBACK_FRAME";
    case(REG_PIN_BRIDGE_TRANS_MEMORY_CALLBACK_SP): return "PIN_BRIDGE_TRANS_MEMORY_CALLBACK_SP";
    case(REG_PIN_BX): return "PIN_BX";
    case(REG_PIN_CH): return "PIN_CH";
    case(REG_PIN_CL): return "PIN_CL";
    case(REG_PIN_CX): return "PIN_CX";
    case(REG_PIN_DF_FLAG): return "PIN_DF_FLAG";
    case(REG_PIN_DH): return "PIN_DH";
    case(REG_PIN_DI): return "PIN_DI";
    case(REG_PIN_DL): return "PIN_DL";
    case(REG_PIN_DX): return "PIN_DX";
    case(REG_PIN_EAX): return "PIN_EAX";
    case(REG_PIN_EBP): return "PIN_EBP";
    case(REG_PIN_EBX): return "PIN_EBX";
    case(REG_PIN_ECX): return "PIN_ECX";
    case(REG_PIN_EDI): return "PIN_EDI";
    case(REG_PIN_EDX): return "PIN_EDX";
    case(REG_PIN_ESI): return "PIN_ESI";
    case(REG_PIN_ESP): return "PIN_ESP";
    case(REG_PIN_FLAGS): return "PIN_FLAGS";
    case(REG_PIN_INDIRREG): return "PIN_INDIRREG";
    case(REG_PIN_IPRELADDR): return "PIN_IPRELADDR";
    case(REG_PIN_MULTI_MEM_ACCESS_AND_REWRITE_EMULATION_INFO_FRAME): return "PIN_MULTI_MEM_ACCESS_AND_REWRITE_EMULATION_INFO_FRAME";
    case(REG_PIN_MXCSR): return "PIN_MXCSR";
    case(REG_PIN_SI): return "PIN_SI";
    case(REG_PIN_SP): return "PIN_SP";
    case(REG_PIN_SPILLPTR): return "PIN_SPILLPTR";
    case(REG_PIN_STATUS_FLAGS): return "PIN_STATUS_FLAGS";
    case(REG_PIN_SYSENTER_RESUMEADDR): return "PIN_SYSENTER_RESUMEADDR";
    case(REG_PIN_T0): return "PIN_T0";
    case(REG_PIN_T0D): return "PIN_T0D";
    case(REG_PIN_T0L): return "PIN_T0L";
    case(REG_PIN_T0W): return "PIN_T0W";
    case(REG_PIN_T1): return "PIN_T1";
    case(REG_PIN_T1D): return "PIN_T1D";
    case(REG_PIN_T1L): return "PIN_T1L";
    case(REG_PIN_T1W): return "PIN_T1W";
    case(REG_PIN_T2): return "PIN_T2";
    case(REG_PIN_T2D): return "PIN_T2D";
    case(REG_PIN_T2L): return "PIN_T2L";
    case(REG_PIN_T2W): return "PIN_T2W";
    case(REG_PIN_T3): return "PIN_T3";
    case(REG_PIN_T3D): return "PIN_T3D";
    case(REG_PIN_T3L): return "PIN_T3L";
    case(REG_PIN_T3W): return "PIN_T3W";
    case(REG_PIN_TRANS_MEMORY_CALLBACK_READ2_ADDR): return "PIN_TRANS_MEMORY_CALLBACK_READ2_ADDR";
    case(REG_PIN_TRANS_MEMORY_CALLBACK_READ_ADDR): return "PIN_TRANS_MEMORY_CALLBACK_READ_ADDR";
    case(REG_PIN_TRANS_MEMORY_CALLBACK_WRITE_ADDR): return "PIN_TRANS_MEMORY_CALLBACK_WRITE_ADDR";
    case(REG_PIN_VMENTER): return "PIN_VMENTER";
    case(REG_PIN_X87): return "PIN_X87";
    case(REG_PIN_XMM0): return "PIN_XMM0";
    case(REG_PIN_XMM1): return "PIN_XMM1";
    case(REG_PIN_XMM2): return "PIN_XMM2";
    case(REG_PIN_XMM3): return "PIN_XMM3";
    case(REG_PIN_XMM4): return "PIN_XMM4";
    case(REG_PIN_XMM5): return "PIN_XMM5";
    case(REG_PIN_XMM6): return "PIN_XMM6";
    case(REG_PIN_XMM7): return "PIN_XMM7";
    case(REG_PIN_YMM0): return "PIN_YMM0";
    case(REG_PIN_YMM1): return "PIN_YMM1";
    case(REG_PIN_YMM2): return "PIN_YMM2";
    case(REG_PIN_YMM3): return "PIN_YMM3";
    case(REG_PIN_YMM4): return "PIN_YMM4";
    case(REG_PIN_YMM5): return "PIN_YMM5";
    case(REG_PIN_YMM6): return "PIN_YMM6";
    case(REG_PIN_YMM7): return "PIN_YMM7";
    case(REG_SEG_CS): return "SEG_CS";
    case(REG_SEG_DS): return "SEG_DS";
    case(REG_SEG_ES): return "SEG_ES";
    case(REG_SEG_FS): return "SEG_FS";
    case(REG_SEG_FS_BASE): return "SEG_FS_BASE";
    case(REG_SEG_FS_VAL): return "SEG_FS_VAL";
    case(REG_SEG_GS): return "SEG_GS";
    case(REG_SEG_GS_BASE): return "SEG_GS_BASE";
    case(REG_SEG_GS_VAL): return "SEG_GS_VAL";
    case(REG_SEG_SS): return "SEG_SS";
    case(REG_SI): return "SI";
    case(REG_SP): return "SP";
    case(REG_ST0): return "ST0";
    case(REG_ST1): return "ST1";
    case(REG_ST2): return "ST2";
    case(REG_ST3): return "ST3";
    case(REG_ST4): return "ST4";
    case(REG_ST5): return "ST5";
    case(REG_ST6): return "ST6";
    case(REG_ST7): return "ST7";
    case(REG_STATUS_FLAGS): return "STATUS_FLAGS";
    case(REG_THREAD_ID): return "THREAD_ID";
    case(REG_TR): return "TR";
    case(REG_TR3): return "TR3";
    case(REG_TR4): return "TR4";
    case(REG_TR5): return "TR5";
    case(REG_TR6): return "TR6";
    case(REG_TR7): return "TR7";
    case(REG_TSSR): return "TSSR";
    case(REG_X87): return "X87";
    case(REG_XMM0): return "XMM0";
    case(REG_XMM1): return "XMM1";
    case(REG_XMM2): return "XMM2";
    case(REG_XMM3): return "XMM3";
    case(REG_XMM4): return "XMM4";
    case(REG_XMM5): return "XMM5";
    case(REG_XMM6): return "XMM6";
    case(REG_XMM7): return "XMM7";
    case(REG_YMM0): return "YMM0";
    case(REG_YMM1): return "YMM1";
    case(REG_YMM2): return "YMM2";
    case(REG_YMM3): return "YMM3";
    case(REG_YMM4): return "YMM4";
    case(REG_YMM5): return "YMM5";
    case(REG_YMM6): return "YMM6";
    case(REG_YMM7): return "YMM7";
  }
error(L, "unknown enum value");
return "never reached";
}
